name: dp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - torch=2.1.1
  - torchvision=0.16.1
  - matplotlib=3.8.1
  - numpy=1.26.0
  - scikit-learn=1.3.2
  - scipy=1.11.3
  - pandas=2.1.3
  - pip:
    - notebook
    - wandb
    - torchinfo
    - plotly~=5.18.0
    - azureml-core~=1.49.0
    - nibabel~=5.1.0
    - opencv-python~=4.8.1.78
